"""Chat router with SSE streaming endpoint."""

import json
import uuid
from typing import AsyncGenerator

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.cache import CacheService, get_cache_service
from app.config import get_settings
from app.crew.crew import get_financial_crew
from app.database import get_db_session
from app.schemas.chat import (
    ChatHistoryResponse,
    ChatMessageSchema,
    ChatRequest,
    ChatStreamEvent,
)
from app.services.chat_service import ChatService

router = APIRouter(prefix="/chat", tags=["chat"])
settings = get_settings()


async def generate_chat_stream(
    request: ChatRequest,
    db_session: AsyncSession,
    cache: CacheService,
) -> AsyncGenerator[str, None]:
    """Generate SSE stream for chat response."""
    chat_service = ChatService(db_session, cache)
    crew = get_financial_crew()

    try:
        # Get or create conversation
        conversation = await chat_service.get_or_create_conversation(
            request.session_id,
            title=request.message[:50] + "..." if len(request.message) > 50 else request.message,
        )

        # Save user message
        await chat_service.add_message(
            conversation.id,
            "user",
            request.message,
        )

        # Send status update
        yield f"data: {json.dumps({'type': 'status', 'content': 'Analyzing your query...'})}\n\n"

        # Check cache for LLM response
        cached_response = await cache.get_llm_response(
            request.message, request.context or ""
        )

        if cached_response:
            # Use cached response
            yield f"data: {json.dumps({'type': 'status', 'content': 'Retrieving cached analysis...'})}\n\n"
            response_content = cached_response
        else:
            # Run crew analysis
            response_chunks = []

            def progress_callback(status: str) -> None:
                """Send progress updates."""
                pass  # Progress updates handled via status messages

            yield f"data: {json.dumps({'type': 'status', 'content': 'Running multi-agent analysis...'})}\n\n"

            # Execute crew analysis
            response_content = await crew.analyze(
                request.message,
                request.context or "",
                progress_callback,
            )

            # Cache the response
            await cache.set_llm_response(
                request.message,
                response_content,
                request.context or "",
            )

        # Stream the response in chunks
        chunk_size = 50
        for i in range(0, len(response_content), chunk_size):
            chunk = response_content[i:i + chunk_size]
            event = ChatStreamEvent(
                type="chunk",
                content=chunk,
            )
            yield f"data: {json.dumps(event.model_dump())}\n\n"

        # Save assistant message
        await chat_service.add_message(
            conversation.id,
            "assistant",
            response_content,
            metadata={"cached": cached_response is not None},
        )

        # Send completion event
        completion_event = ChatStreamEvent(
            type="complete",
            content=response_content,
            metadata={
                "conversation_id": str(conversation.id),
                "cached": cached_response is not None,
            },
        )
        yield f"data: {json.dumps(completion_event.model_dump())}\n\n"

    except Exception as e:
        # Send error event
        error_event = ChatStreamEvent(
            type="error",
            content=str(e),
            metadata={"error_type": type(e).__name__},
        )
        yield f"data: {json.dumps(error_event.model_dump())}\n\n"


@router.post("/stream")
async def chat_stream(
    request: ChatRequest,
    db_session: AsyncSession = Depends(get_db_session),
    cache: CacheService = Depends(get_cache_service),
) -> StreamingResponse:
    """Stream chat response using Server-Sent Events.

    This endpoint accepts a chat message and streams the AI response
    using Server-Sent Events (SSE). The response is generated by a
    multi-agent CrewAI system specialized in financial analysis.
    """
    return StreamingResponse(
        generate_chat_stream(request, db_session, cache),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable nginx buffering
        },
    )


@router.get("/history/{session_id}", response_model=ChatHistoryResponse)
async def get_chat_history(
    session_id: str,
    db_session: AsyncSession = Depends(get_db_session),
    cache: CacheService = Depends(get_cache_service),
) -> ChatHistoryResponse:
    """Get chat history for a session."""
    chat_service = ChatService(db_session, cache)
    conversation = await chat_service.get_conversation_by_session(session_id)

    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")

    return ChatHistoryResponse(
        session_id=session_id,
        conversation_id=conversation.id,
        messages=conversation.messages,
    )


@router.delete("/{conversation_id}")
async def delete_conversation(
    conversation_id: uuid.UUID,
    db_session: AsyncSession = Depends(get_db_session),
    cache: CacheService = Depends(get_cache_service),
) -> dict:
    """Delete a conversation and its messages."""
    chat_service = ChatService(db_session, cache)
    deleted = await chat_service.delete_conversation(conversation_id)

    if not deleted:
        raise HTTPException(status_code=404, detail="Conversation not found")

    return {"message": "Conversation deleted successfully"}
